### PR TITLE
Recreated demo project.

### LINKED ISSUE #33: Example project seems to be broken
I would rather write some tests than correcting the example project.
If one has the use case to implement a date picker dialog, the readme contains enough information of how to use this project (which is pretty simple). So I recommend to just leave it out.

### PR DESCRIPTION
**Pull request by benjohnde**
A bit of restructuring and got the demo project back to work. Reformatted some comments to work with recent Xcode. Closes #33.

Sry for the huge amount of changes. I recreated the whole demo project and cleaned it up (especially removed localization shizzle and all the AppDelegate stubs to focus only on the actual example invocation of the DatePickerDialog).

I also created a shared scheme for the DatePickerDialog itself. Now you have all three parts (Sources, Tests and Demo) in one Xcode project. It is also more feasible to write unit tests and directly see the changes in the demo application.

Cheers!

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @benjohnde, I downloaded your branch and got this:
screen shot 2016-09-19 at 1 02 45 am

**Comment by benjohnde** [comment]
I guess you need to select the framework scheme at first and build it.
Maybe we should put that in the readme. If it does not work out for you I
will look into it later on.

Am 19.09.2016 10:03 vorm. schrieb "Lucas Farah" <notifications@github.com>:

**Comment by lfarah** [comment]
Now it worked. What if instead of making the framework necessary for the example app, we just add the ```DatePickerDialog.swift``` into the Example project?

**Comment by lfarah** [comment]
Again, really thanks for helping the lib! 😄

**Comment by benjohnde** [comment]
I really hate that because changing the library means copying the file into
the demo project. For me it feels like a much cleaner approach to build the
framework and the run the example project. Maybe we can create a symbolic
link but also feels a bit hacky :D

Am 19.09.2016 10:24 vorm. schrieb "Lucas Farah" <notifications@github.com>:

**Comment by lfarah** [comment]
@benjohnde I completely understand your point of view. I think that there are many developers that wouldn't know what building the framework scheme is, so by providing an example app that *just works* is very important for beginners.
On my libs, I always drag the file and remain this unchecked, so we don't have to copy the file every single time:
screen shot 2016-09-19 at 1 28 30 am

**Comment by benjohnde** [comment]
True. Maybe we can create a hard dependency so that the framework gets
built automatically beforehand. I will dig into that.

Am 19.09.2016 10:29 vorm. schrieb "Lucas Farah" <notifications@github.com>:

**Comment by benjohnde** [comment]
Now it should work like magic :) You only need to add the framework to "Linked Frameworks and Libraries" as "required" in the demo target. You can verify it by doing the following:
- Select the framework scheme, clean the build.
- Then remove the entry in "Linked Frameworks and Libraries" from the demo target.
- Now try to build the demo target -> it should break.
- Add the entry again -> build the demo target -> works as intended.

Cheers!

**Comment by lfarah** [comment]
Perfect! Merging this, bumping the version and sending to CocoaPods 👍

**Comment by lfarah** [comment]
Hey @benjohnde, [I'm having problems with CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/5901)

**Comment by benjohnde** [comment]
Hey @lfarah I am not familiar with CocoaPods. I will give Carthage a try later on. But your bug report does not sound like it could be our fault.

**Comment by lfarah** [comment]
It's working now...

**Pull request merged**
