### PR TITLE
Perform changes to convert to Swift 5.

### PR DESCRIPTION
**Pull request by coltonlemmon**
Performed minor changes to UIDatePicker.Mode and UIDevice.orientationDidChangeNotification so the project would build cleanly in Swift 5.

### CODE REVIEW

**Comment by amrangry** [comment]
I would love to have this merge
any idea how i can use it

**Comment by petros9282** [comment]
Hi! Please merge.

**Comment by petros9282** [comment]
> I would love to have this merge
> any idea how i can use it

You can use @coltonlemmon 's fork in cocoapods.

**Comment by viniciussoares** [comment]
3.0 adds support for swift 5.0 :)

**Pull request closed without merging**
