### PR TITLE
Added showCancelButton dialog option

### PR DESCRIPTION
**Pull request by misteral**
Hi, in my case 'Cancel' button not useful. Created optional flag in the class init.

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @misteral, thanks for the PR, really! 👍 
Can you update the README, showcasing this new method?

**Comment by lfarah** [comment]
@squimer what do you think?

**Comment by viniciussoares** [comment]
Thanks @misteral, i'll take a look tomorrow.

In the mean time... This pull request made me wonder, do you guys think is a good idea to move all the parameters to variables and add a delegate? It would look more like how the default components behave.

Something like:

```
let datePicker = DatePicker()
datePicker.title = "Pick your date"
datePicker.defaultDate = Date()
datePicker.mode = .dateAndTime
datePicker.delegate = self
datePicker.present()
```

**Comment by misteral** [comment]
@lfarah, thanks, welcome.  README was updated in PR, please describe if any additionals is necessary.

**Comment by lfarah** [comment]
@viniciussoares please merge if you also approve

**Comment by lfarah** [comment]
@viniciussoares we could add Delegation.... Please open an issue regarding this

**Pull request merged**
