### PR TITLE
Feature/min max dates

### PR DESCRIPTION
**Pull request by madeinqc**
This allows to set a minimum and maximum date as limits for the picker.
The demo was also adjusted to show the usage.

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @madeinqc, now I'm an admin on this repo.
Can you please rebase?

**Comment by madeinqc** [comment]
Sorry for the long delay. The merge is now done, no more conflicts. @lfarah

**Comment by lfarah** [comment]
Thanks for contributing, @madeinqc

**Comment by lfarah** [comment]
Just pushed CocoaPods update

**Pull request merged**
